# Generated by Django 4.1.4 on 2022-12-26 06:29

import bibleAPI.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('userID', models.CharField(max_length=100)),
                ('verses', djongo.models.fields.ArrayField(model_container=bibleAPI.models.Verse)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('verse', models.IntegerField()),
            ],
        ),
    ]
